### ISSUE TITLE
Close site menu when clicking on tag

### ISSUE THREAD

**Issue by Bukama** [nipafx/nipafx.dev#12]
When selecting tags on the left site of the page, you can select multiple and they are combined via `OR` (I know that the `OR` is on purpose).

But when select tags via the navigation, e.g. `Words -> Tags` the selection is overwritten every time, meaning I can't select two tags this way.

Most probably this is also on purpose, but then you should close the tag overlay (from the navigation) to emphasize this. I suggest to do this anyway, because the user can't ready anything after selecting a tag, because the overlay fills the screen and hides the content anyway.

**Comment by nipafx** [comment]
My assumption is that if a user selects _Words_ ~> _Tags_ ~> _..._ in the menu, they want to see blog posts with that tag (and nothing else). Otherwise they could have used the filter on the landing page. So the different behavior is on purpose.

That said, it would be nice if the menu closes when you click an entry (at the moment it doesn't when you're on the landing page), so this issue will track that requirement.
